version: '3.8'

services:
  app:
    container_name: nextjs-pwa-moneymanagement
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8086:3000"
    environment:
      - MONGODB_URI=mongodb://americano-mongo:27017/moneymanagement
      - NODE_ENV=production
      - AUTH_URL=https://mone.widifirmaan.web.id
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    networks:
      - root_default

networks:
  root_default:
    external: true
